### ISSUE TITLE
setTimeout in wemo and lifx plugins

### ISSUE THREAD

**Issue by luisfpinto** [netbeast/plugins#2]
If have seen that the function setTimeout is used in some plugins like wemo or lifx for the discover method. Why is that necessary? Thank you!

**Comment by pablopi** [comment]
There is no setTimeout function on the example plugin. It is used in some plugins, but not by default.

**Comment by luisfpinto** [comment]
Ok is that necessary?

**Comment by pablopi** [comment]
That's because the method discover of 'wemo-client' and 'lifx' modules never ends. So, there is a setTimeout to finish the discovery period (it is a walk around). Using setTimeout is not recommended.
